import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-enterprise-telecom-expense-circuit-recovery",
  "engine": "recovery",
  "title": "Enterprise Telecom Expense & Circuit Recovery",
  "shortTitle": "Telecom Expense Recovery",
  "tagline": "Reconcile every circuit, mobile line, service order, SLA, and carrier invoice",
  "industry": "Enterprise Telecom Expense Management",
  "uiPort": 4572,
  "apiPort": 5572,
  "accent": "#0369a1",
  "currency": "USD",
  "primaryOutcome": "Disconnected, duplicated, misrated, and SLA-affected telecom spend converted into verified credits and avoided cost",
  "valueNarrative": "Connect telecom contracts, service inventories, orders, usage, carrier invoices, taxes, and service performance in one buyer-side recovery system.",
  "calculation": {
    "actualKey": "billedAmount",
    "expectedKey": "supportedAmount",
    "actualLabel": "Carrier Billed Amount",
    "expectedLabel": "Inventory & Contract-Supported Amount",
    "varianceLabel": "Potential recovery or avoided cost",
    "direction": "actual-minus-expected",
    "finding": "Service inventory, contract rate, usage, and SLA evidence indicate recoverable enterprise telecom expense.",
    "actions": [
      "Validate the governing agreement and effective rules",
      "Reconcile transaction-level source evidence",
      "Prepare and submit the recovery or correction package",
      "Track response and reconcile realized financial outcome"
    ]
  }
},[
feature("carrier-contract-and-tariff-library","TER01","Carrier contract and tariff library","Reconcile carrier contract and tariff library using carrier contracts, tariffs, circuit inventories, service orders, mobile usage, invoices, taxes, trouble tickets, and SLA measurements.","Produce a governed carrier contract and tariff library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["carrierAccount","Carrier / Billing Account","text","MetroFiber / BA-88412"],["caseReference","Carrier contract and tariff library Reference","text","TER01-2026-001"],["billedAmount","Carrier Billed Amount","currency",685000],["supportedAmount","Inventory & Contract-Supported Amount","currency",574500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Global WAN portfolio","Mobile workforce account","Contact center circuits","Retail location network","Data center connectivity"]}),
feature("circuit-and-number-inventory","TER02","Circuit and number inventory","Reconcile circuit and number inventory using carrier contracts, tariffs, circuit inventories, service orders, mobile usage, invoices, taxes, trouble tickets, and SLA measurements.","Produce a governed circuit and number inventory decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["carrierAccount","Carrier / Billing Account","text","MetroFiber / BA-88412"],["caseReference","Circuit and number inventory Reference","text","TER02-2026-001"],["billedAmount","Carrier Billed Amount","currency",685000],["supportedAmount","Inventory & Contract-Supported Amount","currency",574500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Global WAN portfolio","Mobile workforce account","Contact center circuits","Retail location network","Data center connectivity"]}),
feature("location-and-cost-center-allocation","TER03","Location and cost-center allocation","Reconcile location and cost-center allocation using carrier contracts, tariffs, circuit inventories, service orders, mobile usage, invoices, taxes, trouble tickets, and SLA measurements.","Produce a governed location and cost-center allocation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["carrierAccount","Carrier / Billing Account","text","MetroFiber / BA-88412"],["caseReference","Location and cost-center allocation Reference","text","TER03-2026-001"],["billedAmount","Carrier Billed Amount","currency",685000],["supportedAmount","Inventory & Contract-Supported Amount","currency",574500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Global WAN portfolio","Mobile workforce account","Contact center circuits","Retail location network","Data center connectivity"]}),
feature("carrier-invoice-ingestion","TER04","Carrier invoice ingestion","Reconcile carrier invoice ingestion using carrier contracts, tariffs, circuit inventories, service orders, mobile usage, invoices, taxes, trouble tickets, and SLA measurements.","Produce a governed carrier invoice ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["carrierAccount","Carrier / Billing Account","text","MetroFiber / BA-88412"],["caseReference","Carrier invoice ingestion Reference","text","TER04-2026-001"],["billedAmount","Carrier Billed Amount","currency",685000],["supportedAmount","Inventory & Contract-Supported Amount","currency",574500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Global WAN portfolio","Mobile workforce account","Contact center circuits","Retail location network","Data center connectivity"]}),
feature("contract-rate-recalculation","TER05","Contract-rate recalculation","Reconcile contract-rate recalculation using carrier contracts, tariffs, circuit inventories, service orders, mobile usage, invoices, taxes, trouble tickets, and SLA measurements.","Produce a governed contract-rate recalculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["carrierAccount","Carrier / Billing Account","text","MetroFiber / BA-88412"],["caseReference","Contract-rate recalculation Reference","text","TER05-2026-001"],["billedAmount","Carrier Billed Amount","currency",685000],["supportedAmount","Inventory & Contract-Supported Amount","currency",574500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Global WAN portfolio","Mobile workforce account","Contact center circuits","Retail location network","Data center connectivity"]}),
feature("disconnected-service-billing-detection","TER06","Disconnected-service billing detection","Reconcile disconnected-service billing detection using carrier contracts, tariffs, circuit inventories, service orders, mobile usage, invoices, taxes, trouble tickets, and SLA measurements.","Produce a governed disconnected-service billing detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["carrierAccount","Carrier / Billing Account","text","MetroFiber / BA-88412"],["caseReference","Disconnected-service billing detection Reference","text","TER06-2026-001"],["billedAmount","Carrier Billed Amount","currency",685000],["supportedAmount","Inventory & Contract-Supported Amount","currency",574500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Global WAN portfolio","Mobile workforce account","Contact center circuits","Retail location network","Data center connectivity"]}),
feature("duplicate-service-detection","TER07","Duplicate service detection","Reconcile duplicate service detection using carrier contracts, tariffs, circuit inventories, service orders, mobile usage, invoices, taxes, trouble tickets, and SLA measurements.","Produce a governed duplicate service detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["carrierAccount","Carrier / Billing Account","text","MetroFiber / BA-88412"],["caseReference","Duplicate service detection Reference","text","TER07-2026-001"],["billedAmount","Carrier Billed Amount","currency",685000],["supportedAmount","Inventory & Contract-Supported Amount","currency",574500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Global WAN portfolio","Mobile workforce account","Contact center circuits","Retail location network","Data center connectivity"]}),
feature("mobile-zero-use-analysis","TER08","Mobile zero-use analysis","Reconcile mobile zero-use analysis using carrier contracts, tariffs, circuit inventories, service orders, mobile usage, invoices, taxes, trouble tickets, and SLA measurements.","Produce a governed mobile zero-use analysis decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["carrierAccount","Carrier / Billing Account","text","MetroFiber / BA-88412"],["caseReference","Mobile zero-use analysis Reference","text","TER08-2026-001"],["billedAmount","Carrier Billed Amount","currency",685000],["supportedAmount","Inventory & Contract-Supported Amount","currency",574500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Global WAN portfolio","Mobile workforce account","Contact center circuits","Retail location network","Data center connectivity"]}),
feature("roaming-and-international-fee-audit","TER09","Roaming and international fee audit","Reconcile roaming and international fee audit using carrier contracts, tariffs, circuit inventories, service orders, mobile usage, invoices, taxes, trouble tickets, and SLA measurements.","Produce a governed roaming and international fee audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["carrierAccount","Carrier / Billing Account","text","MetroFiber / BA-88412"],["caseReference","Roaming and international fee audit Reference","text","TER09-2026-001"],["billedAmount","Carrier Billed Amount","currency",685000],["supportedAmount","Inventory & Contract-Supported Amount","currency",574500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Global WAN portfolio","Mobile workforce account","Contact center circuits","Retail location network","Data center connectivity"]}),
feature("usage-allowance-reconciliation","TER10","Usage allowance reconciliation","Reconcile usage allowance reconciliation using carrier contracts, tariffs, circuit inventories, service orders, mobile usage, invoices, taxes, trouble tickets, and SLA measurements.","Produce a governed usage allowance reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["carrierAccount","Carrier / Billing Account","text","MetroFiber / BA-88412"],["caseReference","Usage allowance reconciliation Reference","text","TER10-2026-001"],["billedAmount","Carrier Billed Amount","currency",685000],["supportedAmount","Inventory & Contract-Supported Amount","currency",574500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Global WAN portfolio","Mobile workforce account","Contact center circuits","Retail location network","Data center connectivity"]}),
feature("tax-and-surcharge-audit","TER11","Tax and surcharge audit","Reconcile tax and surcharge audit using carrier contracts, tariffs, circuit inventories, service orders, mobile usage, invoices, taxes, trouble tickets, and SLA measurements.","Produce a governed tax and surcharge audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["carrierAccount","Carrier / Billing Account","text","MetroFiber / BA-88412"],["caseReference","Tax and surcharge audit Reference","text","TER11-2026-001"],["billedAmount","Carrier Billed Amount","currency",685000],["supportedAmount","Inventory & Contract-Supported Amount","currency",574500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Global WAN portfolio","Mobile workforce account","Contact center circuits","Retail location network","Data center connectivity"]}),
feature("service-level-credit-calculation","TER12","Service-level credit calculation","Reconcile service-level credit calculation using carrier contracts, tariffs, circuit inventories, service orders, mobile usage, invoices, taxes, trouble tickets, and SLA measurements.","Produce a governed service-level credit calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["carrierAccount","Carrier / Billing Account","text","MetroFiber / BA-88412"],["caseReference","Service-level credit calculation Reference","text","TER12-2026-001"],["billedAmount","Carrier Billed Amount","currency",685000],["supportedAmount","Inventory & Contract-Supported Amount","currency",574500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Global WAN portfolio","Mobile workforce account","Contact center circuits","Retail location network","Data center connectivity"]}),
feature("order-to-bill-reconciliation","TER13","Order-to-bill reconciliation","Reconcile order-to-bill reconciliation using carrier contracts, tariffs, circuit inventories, service orders, mobile usage, invoices, taxes, trouble tickets, and SLA measurements.","Produce a governed order-to-bill reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["carrierAccount","Carrier / Billing Account","text","MetroFiber / BA-88412"],["caseReference","Order-to-bill reconciliation Reference","text","TER13-2026-001"],["billedAmount","Carrier Billed Amount","currency",685000],["supportedAmount","Inventory & Contract-Supported Amount","currency",574500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Global WAN portfolio","Mobile workforce account","Contact center circuits","Retail location network","Data center connectivity"]}),
feature("carrier-dispute-workflow","TER14","Carrier dispute workflow","Reconcile carrier dispute workflow using carrier contracts, tariffs, circuit inventories, service orders, mobile usage, invoices, taxes, trouble tickets, and SLA measurements.","Produce a governed carrier dispute workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["carrierAccount","Carrier / Billing Account","text","MetroFiber / BA-88412"],["caseReference","Carrier dispute workflow Reference","text","TER14-2026-001"],["billedAmount","Carrier Billed Amount","currency",685000],["supportedAmount","Inventory & Contract-Supported Amount","currency",574500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Global WAN portfolio","Mobile workforce account","Contact center circuits","Retail location network","Data center connectivity"]}),
feature("refund-and-credit-ledger","TER15","Refund and credit ledger","Reconcile refund and credit ledger using carrier contracts, tariffs, circuit inventories, service orders, mobile usage, invoices, taxes, trouble tickets, and SLA measurements.","Produce a governed refund and credit ledger decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["carrierAccount","Carrier / Billing Account","text","MetroFiber / BA-88412"],["caseReference","Refund and credit ledger Reference","text","TER15-2026-001"],["billedAmount","Carrier Billed Amount","currency",685000],["supportedAmount","Inventory & Contract-Supported Amount","currency",574500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Global WAN portfolio","Mobile workforce account","Contact center circuits","Retail location network","Data center connectivity"]}),
feature("renewal-and-consolidation-analytics","TER16","Renewal and consolidation analytics","Reconcile renewal and consolidation analytics using carrier contracts, tariffs, circuit inventories, service orders, mobile usage, invoices, taxes, trouble tickets, and SLA measurements.","Produce a governed renewal and consolidation analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["carrierAccount","Carrier / Billing Account","text","MetroFiber / BA-88412"],["caseReference","Renewal and consolidation analytics Reference","text","TER16-2026-001"],["billedAmount","Carrier Billed Amount","currency",685000],["supportedAmount","Inventory & Contract-Supported Amount","currency",574500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Global WAN portfolio","Mobile workforce account","Contact center circuits","Retail location network","Data center connectivity"]})
]);
